### ISSUE TITLE
Salesforce Switch Error

### ISSUE THREAD

**Issue by SalesforceBobLightning** [benedwards44/sfswitch#12]
Hi Ben,

I am getting this error when trying to use Salesforce Switch:

There was an error processing your request: Traceback (most recent call last): File "/app/enable_disable/tasks.py", line 130, in get_metadata for component in metadata_client.service.readMetadata('WorkflowRule', query_list)[0]: File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 542, in __call__ return client.invoke(args, kwargs) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 602, in invoke result = self.send(soapenv) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 649, in send result = self.failed(binding, e) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 702, in failed r, p = binding.get_fault(reply) File "/app/.heroku/python/lib/python2.7/site-packages/suds/bindings/binding.py", line 265, in get_fault raise WebFault(p, faultroot) WebFault: Server raised fault: 'UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1241321272-120388 (491286576)'

**Comment by allisonletts** [comment]
I'm getting a similar error. It occurs in Production, but not the full sandbox of the same org.
`There was an error processing your request: Traceback (most recent call last): File "/app/enable_disable/tasks.py", line 130, in get_metadata for component in metadata_client.service.readMetadata('WorkflowRule', query_list)[0]: File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 542, in __call__ return client.invoke(args, kwargs) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 602, in invoke result = self.send(soapenv) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 649, in send result = self.failed(binding, e) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 702, in failed r, p = binding.get_fault(reply) File "/app/.heroku/python/lib/python2.7/site-packages/suds/bindings/binding.py", line 265, in get_fault raise WebFault(p, faultroot) WebFault: Server raised fault: 'UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1059542797-259933 (-1011176768)' 

Please return to the home page and try again.`

**Comment by mlregal** [comment]
I'm getting the same error, only in Production:

Traceback (most recent call last): File "/app/enable_disable/tasks.py", line 130, in get_metadata for component in metadata_client.service.readMetadata('WorkflowRule', query_list)[0]: File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 542, in __call__ return client.invoke(args, kwargs) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 602, in invoke result = self.send(soapenv) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 649, in send result = self.failed(binding, e) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 702, in failed r, p = binding.get_fault(reply) File "/app/.heroku/python/lib/python2.7/site-packages/suds/bindings/binding.py", line 265, in get_fault raise WebFault(p, faultroot) WebFault: Server raised fault: 'UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1597570746-72920 (683869076)'

**Comment by KyleHandley** [comment]
Same error 
Trying to use the tool in a lightning production org.

There was an error processing your request: Traceback (most recent call last): File "/app/enable_disable/tasks.py", line 130, in get_metadata for component in metadata_client.service.readMetadata('WorkflowRule', query_list)[0]: File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 542, in call return client.invoke(args, kwargs) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 602, in invoke result = self.send(soapenv) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 649, in send result = self.failed(binding, e) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 702, in failed r, p = binding.get_fault(reply) File "/app/.heroku/python/lib/python2.7/site-packages/suds/bindings/binding.py", line 265, in get_fault raise WebFault(p, faultroot) WebFault: Server raised fault: 'UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1765614604-52861 (-346804132)'

**Comment by KyleHandley** [comment]
I opened a ticket with SFDC developer support to see if I can get more detail on the error.

**Comment by KyleHandley** [comment]
SFDC Says two of our workflow rules are throwing a null pointer exception.

**Comment by kharrell5** [comment]
Did anyone ever find out what was really causing this error.  I am setting up a user in our production instance and they are getting this error.  However, when I log into Switch, I am able to pull down the metdata without any issues.  The new user is set up with the same permissions as I have.  What could be causing this issue?

**Comment by Techley-git** [comment]
Salesforce says it's a null value being passed somewhere but I haven't been
able to get my own heroku instance up and running yet to test. This code
base has some outdated requirements.txt / framework versions and is missing
a few things (IE need SECRET_KEY env variable). I'm definitely at the edge
of my knowledge and hacking my way beyond if anyone wants to lend a hand!

May your day continue to be filled with awesome,
Kyle Handley

**Comment by kharrell5** [comment]
Thanks Kyle.

I was able to resolve the issue by giving the new user some additional permissions that they needed.

Kathy Harrell
Sr. Salesforce Operations Analyst
kharrell@seismic.com | 919.210.8687
Seismic | www.seismic.com<http://www.seismic.com/>
[cid:image001.jpg@01D6BC49.5CD5FA90]  [cid:image002.jpg@01D6BC49.5CD5FA90]

[cid:image003.png@01D6BC49.5CD5FA90]<https://www.linkedin.com/company/seismic-software/>
[cid:image004.png@01D6BC49.5CD5FA90]<https://twitter.com/SeismicSoftware>
[cid:image005.png@01D6BC49.5CD5FA90]<https://www.instagram.com/seismic_software/>

**Comment by Techley-git** [comment]
What was it? Maybe that can fix mine

May your day continue to be filled with awesome,
Kyle Handley
