### ISSUE TITLE
UNKNOWN_EXCEPTION: An unexpected error occurred

### ISSUE THREAD

**Issue by KyleHandley** [benedwards44/sfswitch#15]
Trying to use the tool in a lightning production org. 

There was an error processing your request: Traceback (most recent call last): File "/app/enable_disable/tasks.py", line 130, in get_metadata for component in metadata_client.service.readMetadata('WorkflowRule', query_list)[0]: File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 542, in __call__ return client.invoke(args, kwargs) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 602, in invoke result = self.send(soapenv) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 649, in send result = self.failed(binding, e) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 702, in failed r, p = binding.get_fault(reply) File "/app/.heroku/python/lib/python2.7/site-packages/suds/bindings/binding.py", line 265, in get_fault raise WebFault(p, faultroot) WebFault: Server raised fault: 'UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1765614604-52861 (-346804132)'

**Comment by KyleHandley** [comment]
duplicate of #12
